var_dependency_cache_key: &var_dependency_cache_key dependency-cache-npm-v1
var_dependency_cache_path: &var_dependency_cache_path ~/.npm

anchor_job_common: &anchor_job_common
  docker:
    - image: circleci/node:8-browsers

anchor_install_deps: &anchor_install_deps
  name: Install Dependencies
  command: npm ci --silent

version: 2
jobs:
  lint:
    <<: *anchor_job_common
    steps:
      - checkout
      - restore_cache:
          key: *var_dependency_cache_key
      - run: *anchor_install_deps
      - save_cache:
          key: *var_dependency_cache_key
          paths:
            - *var_dependency_cache_path
      - run:
          name: Format check
          command: npm run format:check -- --base="origin/master" --head=HEAD --parallel
      - run:
          name: Lint
          command: npm run affected:lint -- --base="origin/master" --head=HEAD --parallel
  test:
    <<: *anchor_job_common
    steps:
      - checkout
      - restore_cache:
          key: *var_dependency_cache_key
      - run: *anchor_install_deps
      - save_cache:
          key: *var_dependency_cache_key
          paths:
            - *var_dependency_cache_path
      - run:
          name: Test
          command: npm run affected:test -- --base="origin/master" --head=HEAD --parallel
  build:
    <<: *anchor_job_common
    steps:
      - checkout
      - restore_cache:
          key: *var_dependency_cache_key
      - run: *anchor_install_deps
      - save_cache:
          key: *var_dependency_cache_key
          paths:
            - *var_dependency_cache_path
      - run:
          name: Build
          command: npm run affected:build -- --base="origin/master" --head=HEAD --parallel

workflows:
  version: 2
  lint_build_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - lint
